---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: dtabs.l5d.io
spec:
  scope: Namespaced
  group: l5d.io
  version: v1alpha1
  names:
    kind: DTab
    plural: dtabs
    singular: dtab
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: namerd-config
  namespace: linkerd
data:
  config.yml: |-
    admin:
      ip: 0.0.0.0
      port: 9991

    namers:
    - kind: io.l5d.k8s
      experimental: true
      host: localhost
      port: 8001

    storage:
      kind: io.l5d.k8s
      host: localhost
      port: 8001
      namespace: linkerd

    interfaces:
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4100
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4180

---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: namerd
  namespace: linkerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namerd
  template:
    metadata:
      labels:
        app: namerd
    spec:
      dnsPolicy: ClusterFirst
      volumes:
      - name: namerd-config
        configMap:
          name: namerd-config
      containers:
      - name: namerd
        image: buoyantio/namerd:1.3.5
        args:
        - /io.buoyant/namerd/config/config.yml
        ports:
        - name: thrift
          containerPort: 4100
        - name: http
          containerPort: 4180
        - name: admin
          containerPort: 9991
        volumeMounts:
        - name: "namerd-config"
          mountPath: "/io.buoyant/namerd/config"
          readOnly: true
      - name: kubectl
        image: buoyantio/kubectl:v1.8.5
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: namerd
  namespace: linkerd
spec:
  selector:
    app: namerd
  # type: LoadBalancer
  ports:
  - name: thrift
    port: 4100
  - name: http
    port: 4180
  - name: admin
    port: 9991
  # loadBalancerSourceRanges:
  # - 167.206.188.2/32    # office IP
  # - 167.206.188.3/32    # office IP
  # - 52.6.132.107/32    # QA1 NATGateway IP
  # - 34.198.14.168/32   # QA2 NATGateway IP
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: namerctl-script
  namespace: linkerd
data:
  createNs.sh: |-
    #!/bin/sh

    set -e

    if namerctl dtab get external > /dev/null 2>&1; then
      echo "external namespace already exists"
    else
      echo "
      /svc/*      => /host;
      " | namerctl dtab create external -
    fi

    if namerctl dtab get internal > /dev/null 2>&1; then
      echo "internal namespace already exists"
    else
      echo "
      /srv        => /#/io.l5d.k8s/default/http;
      /host       => /srv;
      /tmp        => /srv;
      /svc        => /host;
      " | namerctl dtab create internal -
    fi

    if namerctl dtab get grpc-internal > /dev/null 2>&1; then
      echo "grpc-internal namespace already exists"
    else
      echo "
      /srv        => /#/io.l5d.k8s/default/grpc;
      /grpc       => /srv;
      /svc        => /$/io.buoyant.http.domainToPathPfx/grpc;
      " | namerctl dtab create grpc-internal -
    fi
---
kind: Job
apiVersion: batch/v1
metadata:
  name: namerctl
  namespace: linkerd
spec:
  template:
    metadata:
      name: namerctl
    spec:
      volumes:
      - name: namerctl-script
        configMap:
          name: namerctl-script
          defaultMode: 0755
      containers:
      - name: namerctl
        image: linkerd/namerctl:0.8.6
        env:
        - name: NAMERCTL_BASE_URL
          value: http://namerd.linkerd.svc.cluster.local:4180
        command:
        - "/namerctl/createNs.sh"
        volumeMounts:
        - name: "namerctl-script"
          mountPath: "/namerctl"
          readOnly: true
      restartPolicy: OnFailure
